/*
Copyright 2020 Elotl Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	kipv1beta1 "github.com/elotl/kip/pkg/apis/kip/v1beta1"
	versioned "github.com/elotl/kip/pkg/k8sclient/clientset/versioned"
	internalinterfaces "github.com/elotl/kip/pkg/k8sclient/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/elotl/kip/pkg/k8sclient/listers/kip/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CellInformer provides access to a shared informer and lister for
// Cells.
type CellInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.CellLister
}

type cellInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCellInformer constructs a new informer for Cell type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCellInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCellInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredCellInformer constructs a new informer for Cell type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCellInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KiyotV1beta1().Cells().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KiyotV1beta1().Cells().Watch(context.TODO(), options)
			},
		},
		&kipv1beta1.Cell{},
		resyncPeriod,
		indexers,
	)
}

func (f *cellInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCellInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *cellInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kipv1beta1.Cell{}, f.defaultInformer)
}

func (f *cellInformer) Lister() v1beta1.CellLister {
	return v1beta1.NewCellLister(f.Informer().GetIndexer())
}
