/*
Copyright 2019 Elotl Inc.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "github.com/elotl/cloud-instance-provider/pkg/k8sclient/clientset/versioned/typed/kiyot/v1beta2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKiyotV1beta2 struct {
	*testing.Fake
}

func (c *FakeKiyotV1beta2) Cells() v1beta2.CellInterface {
	return &FakeCells{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKiyotV1beta2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
