apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: anka-registry-claim0
  name: anka-registry-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
