apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o registry-manifests
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: anka-registry
  name: anka-registry
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
  selector:
    io.kompose.service: anka-registry
