apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: anka-registry
  name: anka-registry
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
  selector:
    app.kubernetes.io/name: anka-registry
