apiVersion: v1
cloud:
  aws:
    accessKeyID: ""
    secretAccessKey: ""
etcd:
  internal:
    dataDir: /opt/kip/data
cells:
  bootImageSpec:
    owners: 689494258501
    filters: name=elotl-kip-*
    macfilters: name=elotl-kipmac-*
  defaultInstanceType: "t3.nano"
  defaultVolumeSize: "20G"
  nametag: kip
  standbyCells:
    - instanceType: "mac1.metal"
      count: 1
      spot: false
  cellConfig:
    itzoFlag-use-anka: true
  itzo:
    url: http://itzo-kip-dev-download.s3.amazonaws.com
    version: darwin-latest
kubelet:
  cpu: "100"
  memory: "512Gi"
  pods: "200"
