apiVersion: v1
kind: Service
metadata:
  name: provider
  labels:
    app: kip-provider
spec:
  ports:
  - port: 10250
    name: kubelet
  - port: 10255
    name: kubelet-readonly
  selector:
    app: kip-provider
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: provider
  labels:
    app: kip-provider
spec:
  serviceName: provider
  replicas: 1
  selector:
    matchLabels:
      app: kip-provider
  template:
    metadata:
      labels:
        app: kip-provider
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - kip-provider
            topologyKey: failure-domain.beta.kubernetes.io/zone
      initContainers:
      - command:
        - bash
        - -c
        - mkdir -p $(CERT_DIR) && /opt/csr/get-cert.sh
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CERT_DIR
          value: /data/kubelet-pki
        image: elotl/init-cert:latest
        imagePullPolicy: Always
        name: init-cert
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      containers:
      - command:
        - /kip
        - --provider
        - kip
        - --provider-config
        - /etc/kip/provider.yaml
        - --network-agent-secret
        - $(KIP_NAMESPACE)/$(NETWORK_AGENT_SERVICE_ACCOUNT)
        - --disable-taint
        - --klog.logtostderr
        - --klog.v=2
        - --metrics-addr=:10255
        - --nodename=$(VKUBELET_NODE_NAME)
        image: elotl/kip:v1.0.6-34-gcd02f60-dirty
        imagePullPolicy: Always
        name: kip
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: VKUBELET_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: APISERVER_CERT_LOCATION
          value: /opt/kip/data/kubelet-pki/$(VKUBELET_NODE_NAME).crt
        - name: APISERVER_KEY_LOCATION
          value: /opt/kip/data/kubelet-pki/$(VKUBELET_NODE_NAME).key
        resources:
          limits:
            cpu: "2"
            memory: "1Gi"
          requests:
            cpu: "10m"
            memory: "100Mi"
        volumeMounts:
        - name: data
          mountPath: /opt/kip/data
        - name: provider-yaml
          mountPath: /etc/kip
        - name: macos-init-sh
          mountPath: /usr/local/bin
        - name: xtables-lock
          mountPath: /run/xtables.lock
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        securityContext:
          privileged: true
      - command:
        - /bin/sh
        - -c
        - exec kube-proxy --oom-score-adj=-998 --bind-address=127.0.0.1 --v=2
        image: k8s.gcr.io/kube-proxy:v1.18.3
        imagePullPolicy: IfNotPresent
        name: kube-proxy
        resources:
          requests:
            cpu: 100m
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: provider
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: provider-data
      - name: provider-yaml
        configMap:
          name: config
          items:
          - key: provider.yaml
            path: provider.yaml
            mode: 0600
      - name: macos-init-sh
        configMap:
          name: cloudinit
          items:
          - key: cloudinit.sh
            path: cloudinit.sh
            mode: 0755
      - name: xtables-lock
        hostPath:
          path: /run/kip-xtables.lock
          type: FileOrCreate
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: ""
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
