apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pricing-updater
  namespace: default
  labels:
    app.kubernetes.io/name: pricing-updater
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pricing-updater
          containers:
            - name: updater
              image: 689494258501.dkr.ecr.us-east-1.amazonaws.com/elotl/pricing-updater:94a3992
              # specify your provider and region here
              command: ["./pricing-updater", "-provider", "amazon", "-region", "us-east-1", "-update-configmap"]
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
