# aws-registry-credential-cron.yaml

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: aws-registry-credential-cron
spec:
  schedule: "* */8 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          serviceAccountName: default
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          containers:
            - name: kubectl
              imagePullPolicy: IfNotPresent
              image: xynova/aws-kubectl:latest
              envFrom:
                - secretRef:
                    name: aws-secret
              command:
                - "/bin/sh"
                - "-c"
                - |
                  # create docker login information by aws ecr get-login command
                  DOCKER_REGISTRY_SERVER=https://689494258501.dkr.ecr.us-east-1.amazonaws.com
                  DOCKER_USER=AWS
                  DOCKER_PASSWORD=$(aws ecr get-login --region us-east-1 --registry-ids 689494258501 | cut -d' ' -f6)
                  # delete old secret
                  kubectl delete secret aws-registry || true
                  # create new one by run docker login information
                  kubectl create secret docker-registry aws-registry \
                  --docker-server=$DOCKER_REGISTRY_SERVER \
                  --docker-username=$DOCKER_USER \
                  --docker-password=$DOCKER_PASSWORD \
                  --docker-email=no@email.local
                  # set default pullSecret of service account default is aws-registry
                  kubectl patch serviceaccount default -p '{"imagePullSecrets":[{"name":"aws-registry"}]}