---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pricing-updater
  namespace: default
  labels:
    app.kubernetes.io/name: pricing-updater
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pricing-updater
  namespace: default
  labels:
    app.kubernetes.io/name: pricing-updater
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pricing-updater
  namespace: default
  labels:
    app.kubernetes.io/name: pricing-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pricing-updater
subjects:
  - kind: ServiceAccount
    name: pricing-updater
    namespace: default
