apiVersion: v1
etcd:
  internal:
    dataDir: /opt/kip/data
cells:
  defaultVolumeSize: "600G"
  defaultIAMPermissions: "kip-mac-ssm"
  defaultInstanceType: "t3.nano"
  useCloudParameterStore: true
  nametag: kip
  bootImageSpec:
    imageIDs: ami-051d588cea9ac504a
  cellConfig:
    itzoFlag-use-anka: true
  itzo:
    url: https://itzo-kip-dev-download.s3.amazonaws.com
    version: darwin-876
