apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: provider
spec:
  template:
    spec:
      containers:
        - name: kip
          image: elotl/kip:v1.0.6-82-g424d918
      volumes:
      - name: provider-yaml
        configMap:
          name: config
          items:
          - key: cloudinit.yaml
            path: cloudinit.yaml
            mode: 0600
          - key: provider.yaml
            path: provider.yaml
            mode: 0600
