/*
Copyright 2019 Elotl Inc.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// CellListerExpansion allows custom methods to be added to
// CellLister.
type CellListerExpansion interface{}
