// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clientapi.proto

package clientapi

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Manifest             []byte   `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetManifest() []byte {
	if m != nil {
		return m.Manifest
	}
	return nil
}

type UpdateRequest struct {
	Manifest             []byte   `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{1}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetManifest() []byte {
	if m != nil {
		return m.Manifest
	}
	return nil
}

type GetRequest struct {
	Kind                 []byte   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 []byte   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{2}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKind() []byte {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *GetRequest) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type DeleteRequest struct {
	Kind                 []byte   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name                 []byte   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cascade              bool     `protobuf:"varint,3,opt,name=cascade,proto3" json:"cascade,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{3}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetKind() []byte {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *DeleteRequest) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *DeleteRequest) GetCascade() bool {
	if m != nil {
		return m.Cascade
	}
	return false
}

type DumpRequest struct {
	Kind                 []byte   `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpRequest) Reset()         { *m = DumpRequest{} }
func (m *DumpRequest) String() string { return proto.CompactTextString(m) }
func (*DumpRequest) ProtoMessage()    {}
func (*DumpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{4}
}

func (m *DumpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpRequest.Unmarshal(m, b)
}
func (m *DumpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpRequest.Marshal(b, m, deterministic)
}
func (m *DumpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpRequest.Merge(m, src)
}
func (m *DumpRequest) XXX_Size() int {
	return xxx_messageInfo_DumpRequest.Size(m)
}
func (m *DumpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpRequest proto.InternalMessageInfo

func (m *DumpRequest) GetKind() []byte {
	if m != nil {
		return m.Kind
	}
	return nil
}

type APIReply struct {
	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body   []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// Warnings are printed by the client to stderr
	Warning              []byte   `protobuf:"bytes,3,opt,name=warning,proto3" json:"warning,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APIReply) Reset()         { *m = APIReply{} }
func (m *APIReply) String() string { return proto.CompactTextString(m) }
func (*APIReply) ProtoMessage()    {}
func (*APIReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{5}
}

func (m *APIReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIReply.Unmarshal(m, b)
}
func (m *APIReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIReply.Marshal(b, m, deterministic)
}
func (m *APIReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIReply.Merge(m, src)
}
func (m *APIReply) XXX_Size() int {
	return xxx_messageInfo_APIReply.Size(m)
}
func (m *APIReply) XXX_DiscardUnknown() {
	xxx_messageInfo_APIReply.DiscardUnknown(m)
}

var xxx_messageInfo_APIReply proto.InternalMessageInfo

func (m *APIReply) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *APIReply) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *APIReply) GetWarning() []byte {
	if m != nil {
		return m.Warning
	}
	return nil
}

type VersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionRequest) Reset()         { *m = VersionRequest{} }
func (m *VersionRequest) String() string { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()    {}
func (*VersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{6}
}

func (m *VersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionRequest.Unmarshal(m, b)
}
func (m *VersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionRequest.Marshal(b, m, deterministic)
}
func (m *VersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionRequest.Merge(m, src)
}
func (m *VersionRequest) XXX_Size() int {
	return xxx_messageInfo_VersionRequest.Size(m)
}
func (m *VersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VersionRequest proto.InternalMessageInfo

type VersionReply struct {
	VersionInfo          []byte   `protobuf:"bytes,1,opt,name=versionInfo,proto3" json:"versionInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionReply) Reset()         { *m = VersionReply{} }
func (m *VersionReply) String() string { return proto.CompactTextString(m) }
func (*VersionReply) ProtoMessage()    {}
func (*VersionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{7}
}

func (m *VersionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionReply.Unmarshal(m, b)
}
func (m *VersionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionReply.Marshal(b, m, deterministic)
}
func (m *VersionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionReply.Merge(m, src)
}
func (m *VersionReply) XXX_Size() int {
	return xxx_messageInfo_VersionReply.Size(m)
}
func (m *VersionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionReply.DiscardUnknown(m)
}

var xxx_messageInfo_VersionReply proto.InternalMessageInfo

func (m *VersionReply) GetVersionInfo() []byte {
	if m != nil {
		return m.VersionInfo
	}
	return nil
}

type IsLeaderRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsLeaderRequest) Reset()         { *m = IsLeaderRequest{} }
func (m *IsLeaderRequest) String() string { return proto.CompactTextString(m) }
func (*IsLeaderRequest) ProtoMessage()    {}
func (*IsLeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{8}
}

func (m *IsLeaderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsLeaderRequest.Unmarshal(m, b)
}
func (m *IsLeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsLeaderRequest.Marshal(b, m, deterministic)
}
func (m *IsLeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsLeaderRequest.Merge(m, src)
}
func (m *IsLeaderRequest) XXX_Size() int {
	return xxx_messageInfo_IsLeaderRequest.Size(m)
}
func (m *IsLeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsLeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsLeaderRequest proto.InternalMessageInfo

type IsLeaderReply struct {
	IsLeader             bool     `protobuf:"varint,1,opt,name=isLeader,proto3" json:"isLeader,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsLeaderReply) Reset()         { *m = IsLeaderReply{} }
func (m *IsLeaderReply) String() string { return proto.CompactTextString(m) }
func (*IsLeaderReply) ProtoMessage()    {}
func (*IsLeaderReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{9}
}

func (m *IsLeaderReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsLeaderReply.Unmarshal(m, b)
}
func (m *IsLeaderReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsLeaderReply.Marshal(b, m, deterministic)
}
func (m *IsLeaderReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsLeaderReply.Merge(m, src)
}
func (m *IsLeaderReply) XXX_Size() int {
	return xxx_messageInfo_IsLeaderReply.Size(m)
}
func (m *IsLeaderReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IsLeaderReply.DiscardUnknown(m)
}

var xxx_messageInfo_IsLeaderReply proto.InternalMessageInfo

func (m *IsLeaderReply) GetIsLeader() bool {
	if m != nil {
		return m.IsLeader
	}
	return false
}

type LogsRequest struct {
	ResourceName         string   `protobuf:"bytes,1,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	ItemName             string   `protobuf:"bytes,2,opt,name=itemName,proto3" json:"itemName,omitempty"`
	Lines                int32    `protobuf:"varint,3,opt,name=lines,proto3" json:"lines,omitempty"`
	Limitbytes           int32    `protobuf:"varint,4,opt,name=limitbytes,proto3" json:"limitbytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogsRequest) Reset()         { *m = LogsRequest{} }
func (m *LogsRequest) String() string { return proto.CompactTextString(m) }
func (*LogsRequest) ProtoMessage()    {}
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{10}
}

func (m *LogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogsRequest.Unmarshal(m, b)
}
func (m *LogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogsRequest.Marshal(b, m, deterministic)
}
func (m *LogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogsRequest.Merge(m, src)
}
func (m *LogsRequest) XXX_Size() int {
	return xxx_messageInfo_LogsRequest.Size(m)
}
func (m *LogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogsRequest proto.InternalMessageInfo

func (m *LogsRequest) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *LogsRequest) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

func (m *LogsRequest) GetLines() int32 {
	if m != nil {
		return m.Lines
	}
	return 0
}

func (m *LogsRequest) GetLimitbytes() int32 {
	if m != nil {
		return m.Limitbytes
	}
	return 0
}

type DeployRequest struct {
	ResourceName         string   `protobuf:"bytes,1,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	ItemName             string   `protobuf:"bytes,2,opt,name=itemName,proto3" json:"itemName,omitempty"`
	PackageData          []byte   `protobuf:"bytes,3,opt,name=packageData,proto3" json:"packageData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeployRequest) Reset()         { *m = DeployRequest{} }
func (m *DeployRequest) String() string { return proto.CompactTextString(m) }
func (*DeployRequest) ProtoMessage()    {}
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{11}
}

func (m *DeployRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeployRequest.Unmarshal(m, b)
}
func (m *DeployRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeployRequest.Marshal(b, m, deterministic)
}
func (m *DeployRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeployRequest.Merge(m, src)
}
func (m *DeployRequest) XXX_Size() int {
	return xxx_messageInfo_DeployRequest.Size(m)
}
func (m *DeployRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeployRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeployRequest proto.InternalMessageInfo

func (m *DeployRequest) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *DeployRequest) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

func (m *DeployRequest) GetPackageData() []byte {
	if m != nil {
		return m.PackageData
	}
	return nil
}

type StreamLogsRequest struct {
	Pod                  string   `protobuf:"bytes,1,opt,name=Pod,proto3" json:"Pod,omitempty"`
	Unit                 string   `protobuf:"bytes,2,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Metadata             bool     `protobuf:"varint,3,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamLogsRequest) Reset()         { *m = StreamLogsRequest{} }
func (m *StreamLogsRequest) String() string { return proto.CompactTextString(m) }
func (*StreamLogsRequest) ProtoMessage()    {}
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{12}
}

func (m *StreamLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamLogsRequest.Unmarshal(m, b)
}
func (m *StreamLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamLogsRequest.Marshal(b, m, deterministic)
}
func (m *StreamLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamLogsRequest.Merge(m, src)
}
func (m *StreamLogsRequest) XXX_Size() int {
	return xxx_messageInfo_StreamLogsRequest.Size(m)
}
func (m *StreamLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamLogsRequest proto.InternalMessageInfo

func (m *StreamLogsRequest) GetPod() string {
	if m != nil {
		return m.Pod
	}
	return ""
}

func (m *StreamLogsRequest) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *StreamLogsRequest) GetMetadata() bool {
	if m != nil {
		return m.Metadata
	}
	return false
}

type ConsoleStreamMsg struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsoleStreamMsg) Reset()         { *m = ConsoleStreamMsg{} }
func (m *ConsoleStreamMsg) String() string { return proto.CompactTextString(m) }
func (*ConsoleStreamMsg) ProtoMessage()    {}
func (*ConsoleStreamMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{13}
}

func (m *ConsoleStreamMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsoleStreamMsg.Unmarshal(m, b)
}
func (m *ConsoleStreamMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsoleStreamMsg.Marshal(b, m, deterministic)
}
func (m *ConsoleStreamMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsoleStreamMsg.Merge(m, src)
}
func (m *ConsoleStreamMsg) XXX_Size() int {
	return xxx_messageInfo_ConsoleStreamMsg.Size(m)
}
func (m *ConsoleStreamMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsoleStreamMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ConsoleStreamMsg proto.InternalMessageInfo

func (m *ConsoleStreamMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type StreamMsg struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Error                []byte   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMsg) Reset()         { *m = StreamMsg{} }
func (m *StreamMsg) String() string { return proto.CompactTextString(m) }
func (*StreamMsg) ProtoMessage()    {}
func (*StreamMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_76c811cce3b5e496, []int{14}
}

func (m *StreamMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMsg.Unmarshal(m, b)
}
func (m *StreamMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMsg.Marshal(b, m, deterministic)
}
func (m *StreamMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMsg.Merge(m, src)
}
func (m *StreamMsg) XXX_Size() int {
	return xxx_messageInfo_StreamMsg.Size(m)
}
func (m *StreamMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMsg.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMsg proto.InternalMessageInfo

func (m *StreamMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StreamMsg) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DumpRequest)(nil), "DumpRequest")
	proto.RegisterType((*APIReply)(nil), "APIReply")
	proto.RegisterType((*VersionRequest)(nil), "VersionRequest")
	proto.RegisterType((*VersionReply)(nil), "VersionReply")
	proto.RegisterType((*IsLeaderRequest)(nil), "IsLeaderRequest")
	proto.RegisterType((*IsLeaderReply)(nil), "IsLeaderReply")
	proto.RegisterType((*LogsRequest)(nil), "LogsRequest")
	proto.RegisterType((*DeployRequest)(nil), "DeployRequest")
	proto.RegisterType((*StreamLogsRequest)(nil), "StreamLogsRequest")
	proto.RegisterType((*ConsoleStreamMsg)(nil), "ConsoleStreamMsg")
	proto.RegisterType((*StreamMsg)(nil), "StreamMsg")
}

func init() { proto.RegisterFile("clientapi.proto", fileDescriptor_76c811cce3b5e496) }

var fileDescriptor_76c811cce3b5e496 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5b, 0x4f, 0xdb, 0x30,
	0x18, 0x25, 0x6b, 0x29, 0xe9, 0xd7, 0x0b, 0xc5, 0x9a, 0xa6, 0xaa, 0x0f, 0x5b, 0xb1, 0x18, 0xab,
	0x84, 0x64, 0x55, 0xbb, 0xfc, 0x00, 0x04, 0x08, 0xa1, 0x01, 0x62, 0x99, 0xd8, 0xbb, 0x49, 0x3e,
	0x3a, 0x8b, 0x24, 0x0e, 0xb1, 0xbb, 0xad, 0xcf, 0xfb, 0xbd, 0xfb, 0x0f, 0x93, 0x9d, 0x4b, 0xe3,
	0x21, 0x55, 0x3c, 0xec, 0xcd, 0xe7, 0xf4, 0xe4, 0x3b, 0xbe, 0x9c, 0x53, 0xd8, 0x0d, 0x63, 0x81,
	0xa9, 0xe6, 0x99, 0x60, 0x59, 0x2e, 0xb5, 0xa4, 0x47, 0x30, 0x38, 0xc9, 0x91, 0x6b, 0x0c, 0xf0,
	0x71, 0x89, 0x4a, 0x93, 0x09, 0xf8, 0x09, 0x4f, 0xc5, 0x3d, 0x2a, 0x3d, 0xf6, 0xa6, 0xde, 0xac,
	0x1f, 0xd4, 0xd8, 0x88, 0x6f, 0xb3, 0xe8, 0x99, 0xe2, 0x8f, 0x00, 0xe7, 0xa8, 0x2b, 0x25, 0x81,
	0xf6, 0x83, 0x48, 0xa3, 0x52, 0x65, 0xd7, 0x86, 0x4b, 0x79, 0x82, 0xe3, 0x17, 0x05, 0x67, 0xd6,
	0xf4, 0x0b, 0x0c, 0x4e, 0x31, 0xc6, 0xb5, 0xc5, 0x33, 0x3f, 0x24, 0x63, 0xd8, 0x09, 0xb9, 0x0a,
	0x79, 0x84, 0xe3, 0xd6, 0xd4, 0x9b, 0xf9, 0x41, 0x05, 0xe9, 0x3e, 0xf4, 0x4e, 0x97, 0x49, 0xb6,
	0x61, 0x20, 0xbd, 0x01, 0xff, 0xf8, 0xe6, 0x22, 0xc0, 0x2c, 0x5e, 0x91, 0x57, 0xd0, 0x51, 0x9a,
	0xeb, 0xa5, 0xb2, 0x8a, 0xed, 0xa0, 0x44, 0xe6, 0xbb, 0x3b, 0x19, 0xad, 0x2a, 0x53, 0xb3, 0x36,
	0xa6, 0x3f, 0x79, 0x9e, 0x8a, 0x74, 0x61, 0x4d, 0xfb, 0x41, 0x05, 0xe9, 0x08, 0x86, 0xdf, 0x30,
	0x57, 0x42, 0xa6, 0xa5, 0x2f, 0x9d, 0x43, 0xbf, 0x66, 0x8c, 0xcf, 0x14, 0x7a, 0x3f, 0x0a, 0x7c,
	0x91, 0xde, 0xcb, 0x72, 0x3b, 0x4d, 0x8a, 0xee, 0xc1, 0xee, 0x85, 0xba, 0x44, 0x1e, 0x61, 0x5e,
	0x0d, 0x39, 0x82, 0xc1, 0x9a, 0x32, 0x53, 0x26, 0xe0, 0x8b, 0x92, 0xb0, 0x23, 0xfc, 0xa0, 0xc6,
	0xf4, 0xb7, 0x07, 0xbd, 0x4b, 0xb9, 0x50, 0xd5, 0xc9, 0x29, 0xf4, 0x73, 0x54, 0x72, 0x99, 0x87,
	0x78, 0x6d, 0xae, 0xcf, 0xe8, 0xbb, 0x81, 0xc3, 0xd9, 0x79, 0x1a, 0x93, 0xeb, 0xea, 0x7a, 0xbb,
	0x41, 0x8d, 0xc9, 0x4b, 0xd8, 0x8e, 0x45, 0x8a, 0xca, 0x9e, 0x75, 0x3b, 0x28, 0x00, 0x79, 0x0d,
	0x10, 0x8b, 0x44, 0xe8, 0xbb, 0x95, 0x46, 0x35, 0x6e, 0xdb, 0x9f, 0x1a, 0x0c, 0x7d, 0x34, 0x2f,
	0x9a, 0xc5, 0x72, 0xf5, 0xbf, 0xb6, 0x31, 0x85, 0x5e, 0xc6, 0xc3, 0x07, 0xbe, 0xc0, 0x53, 0xae,
	0x79, 0x79, 0xf1, 0x4d, 0x8a, 0xde, 0xc2, 0xde, 0x57, 0x9d, 0x23, 0x4f, 0x9a, 0xa7, 0x1f, 0x41,
	0xeb, 0x46, 0x46, 0xa5, 0x9b, 0x59, 0x9a, 0x17, 0xbd, 0x4d, 0x85, 0x2e, 0x0d, 0xec, 0xda, 0x18,
	0x5f, 0xa1, 0xe6, 0x51, 0x35, 0xd9, 0x0f, 0x6a, 0x4c, 0x0f, 0x61, 0x74, 0x22, 0x53, 0x25, 0x63,
	0x2c, 0xa6, 0x5f, 0xa9, 0x85, 0x99, 0x61, 0x77, 0x51, 0xa6, 0xc9, 0xda, 0x7f, 0x82, 0xee, 0x46,
	0x81, 0xb9, 0xc8, 0xb3, 0x3c, 0x97, 0x79, 0x99, 0xa5, 0x02, 0xbc, 0xff, 0xd3, 0x82, 0xd6, 0x67,
	0x91, 0x11, 0x66, 0x8b, 0x53, 0x66, 0x85, 0xec, 0x32, 0x37, 0x47, 0x93, 0x01, 0x6b, 0xc6, 0x88,
	0x6e, 0x11, 0x06, 0x7e, 0x95, 0x09, 0x32, 0x62, 0xff, 0x24, 0x66, 0x32, 0x64, 0x4e, 0x60, 0xe8,
	0x16, 0x79, 0x0b, 0x9d, 0xa2, 0xf2, 0x64, 0xc8, 0x9c, 0xee, 0x4f, 0xba, 0xac, 0x6a, 0x41, 0x21,
	0x2b, 0xca, 0x4e, 0x86, 0xcc, 0x69, 0xbd, 0x2b, 0x7b, 0x03, 0xad, 0x73, 0xd4, 0xa4, 0xc7, 0xd6,
	0x65, 0x7f, 0x32, 0xa7, 0x68, 0x34, 0x19, 0x32, 0xa7, 0xda, 0xae, 0xec, 0x00, 0x76, 0xce, 0x51,
	0x9b, 0x07, 0x23, 0x7d, 0xd6, 0x78, 0x37, 0x57, 0xb5, 0x0f, 0x6d, 0xd3, 0x65, 0xd2, 0x67, 0x8d,
	0x4a, 0xbb, 0x92, 0x77, 0xc6, 0xcf, 0xe4, 0xcd, 0xfa, 0x35, 0x82, 0xe7, 0xc8, 0x66, 0x1e, 0x99,
	0x03, 0xac, 0x53, 0x42, 0x08, 0x7b, 0x12, 0x99, 0x09, 0xb0, 0xfa, 0x1d, 0xe9, 0xd6, 0xdc, 0x23,
	0x07, 0xd0, 0x3e, 0xfb, 0x85, 0x21, 0x69, 0xf0, 0xae, 0x66, 0xe6, 0xcd, 0x3d, 0x72, 0x08, 0x9d,
	0x63, 0xad, 0x79, 0xf8, 0x7d, 0xb3, 0xee, 0xae, 0x63, 0xff, 0x81, 0x3f, 0xfc, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x87, 0xdf, 0x3c, 0x11, 0x94, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KipClient is the client API for Kip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KipClient interface {
	// Get Server Version.
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionReply, error)
	// Asks the server if it is the leader.
	IsLeader(ctx context.Context, in *IsLeaderRequest, opts ...grpc.CallOption) (*IsLeaderReply, error)
	// Create given resource on cloud backend.
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*APIReply, error)
	// Update given resource on cloud backend.
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*APIReply, error)
	// Get the given resource
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*APIReply, error)
	// Get the given resource
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*APIReply, error)
	// Get logs of a given pod.
	GetLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*APIReply, error)
	// Dump controller status.
	Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (*APIReply, error)
	// Deploy a Kip package for a unit in a running pod.
	Deploy(ctx context.Context, opts ...grpc.CallOption) (Kip_DeployClient, error)
	// Stream logs from a running pod
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (Kip_StreamLogsClient, error)
	// Execute a command in the context of a unit
	Exec(ctx context.Context, opts ...grpc.CallOption) (Kip_ExecClient, error)
	// Attach to stdin, stdout and stderr of a running pod
	Attach(ctx context.Context, opts ...grpc.CallOption) (Kip_AttachClient, error)
}

type kipClient struct {
	cc *grpc.ClientConn
}

func NewKipClient(cc *grpc.ClientConn) KipClient {
	return &kipClient{cc}
}

func (c *kipClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionReply, error) {
	out := new(VersionReply)
	err := c.cc.Invoke(ctx, "/Kip/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kipClient) IsLeader(ctx context.Context, in *IsLeaderRequest, opts ...grpc.CallOption) (*IsLeaderReply, error) {
	out := new(IsLeaderReply)
	err := c.cc.Invoke(ctx, "/Kip/IsLeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kipClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*APIReply, error) {
	out := new(APIReply)
	err := c.cc.Invoke(ctx, "/Kip/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kipClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*APIReply, error) {
	out := new(APIReply)
	err := c.cc.Invoke(ctx, "/Kip/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kipClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*APIReply, error) {
	out := new(APIReply)
	err := c.cc.Invoke(ctx, "/Kip/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kipClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*APIReply, error) {
	out := new(APIReply)
	err := c.cc.Invoke(ctx, "/Kip/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kipClient) GetLogs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (*APIReply, error) {
	out := new(APIReply)
	err := c.cc.Invoke(ctx, "/Kip/GetLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kipClient) Dump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (*APIReply, error) {
	out := new(APIReply)
	err := c.cc.Invoke(ctx, "/Kip/Dump", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kipClient) Deploy(ctx context.Context, opts ...grpc.CallOption) (Kip_DeployClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Kip_serviceDesc.Streams[0], "/Kip/Deploy", opts...)
	if err != nil {
		return nil, err
	}
	x := &kipDeployClient{stream}
	return x, nil
}

type Kip_DeployClient interface {
	Send(*DeployRequest) error
	CloseAndRecv() (*APIReply, error)
	grpc.ClientStream
}

type kipDeployClient struct {
	grpc.ClientStream
}

func (x *kipDeployClient) Send(m *DeployRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *kipDeployClient) CloseAndRecv() (*APIReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(APIReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kipClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (Kip_StreamLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Kip_serviceDesc.Streams[1], "/Kip/StreamLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &kipStreamLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Kip_StreamLogsClient interface {
	Recv() (*StreamMsg, error)
	grpc.ClientStream
}

type kipStreamLogsClient struct {
	grpc.ClientStream
}

func (x *kipStreamLogsClient) Recv() (*StreamMsg, error) {
	m := new(StreamMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kipClient) Exec(ctx context.Context, opts ...grpc.CallOption) (Kip_ExecClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Kip_serviceDesc.Streams[2], "/Kip/Exec", opts...)
	if err != nil {
		return nil, err
	}
	x := &kipExecClient{stream}
	return x, nil
}

type Kip_ExecClient interface {
	Send(*StreamMsg) error
	Recv() (*StreamMsg, error)
	grpc.ClientStream
}

type kipExecClient struct {
	grpc.ClientStream
}

func (x *kipExecClient) Send(m *StreamMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *kipExecClient) Recv() (*StreamMsg, error) {
	m := new(StreamMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kipClient) Attach(ctx context.Context, opts ...grpc.CallOption) (Kip_AttachClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Kip_serviceDesc.Streams[3], "/Kip/Attach", opts...)
	if err != nil {
		return nil, err
	}
	x := &kipAttachClient{stream}
	return x, nil
}

type Kip_AttachClient interface {
	Send(*StreamMsg) error
	Recv() (*StreamMsg, error)
	grpc.ClientStream
}

type kipAttachClient struct {
	grpc.ClientStream
}

func (x *kipAttachClient) Send(m *StreamMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *kipAttachClient) Recv() (*StreamMsg, error) {
	m := new(StreamMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KipServer is the server API for Kip service.
type KipServer interface {
	// Get Server Version.
	GetVersion(context.Context, *VersionRequest) (*VersionReply, error)
	// Asks the server if it is the leader.
	IsLeader(context.Context, *IsLeaderRequest) (*IsLeaderReply, error)
	// Create given resource on cloud backend.
	Create(context.Context, *CreateRequest) (*APIReply, error)
	// Update given resource on cloud backend.
	Update(context.Context, *UpdateRequest) (*APIReply, error)
	// Get the given resource
	Get(context.Context, *GetRequest) (*APIReply, error)
	// Get the given resource
	Delete(context.Context, *DeleteRequest) (*APIReply, error)
	// Get logs of a given pod.
	GetLogs(context.Context, *LogsRequest) (*APIReply, error)
	// Dump controller status.
	Dump(context.Context, *DumpRequest) (*APIReply, error)
	// Deploy a Kip package for a unit in a running pod.
	Deploy(Kip_DeployServer) error
	// Stream logs from a running pod
	StreamLogs(*StreamLogsRequest, Kip_StreamLogsServer) error
	// Execute a command in the context of a unit
	Exec(Kip_ExecServer) error
	// Attach to stdin, stdout and stderr of a running pod
	Attach(Kip_AttachServer) error
}

// UnimplementedKipServer can be embedded to have forward compatible implementations.
type UnimplementedKipServer struct {
}

func (*UnimplementedKipServer) GetVersion(ctx context.Context, req *VersionRequest) (*VersionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (*UnimplementedKipServer) IsLeader(ctx context.Context, req *IsLeaderRequest) (*IsLeaderReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsLeader not implemented")
}
func (*UnimplementedKipServer) Create(ctx context.Context, req *CreateRequest) (*APIReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedKipServer) Update(ctx context.Context, req *UpdateRequest) (*APIReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedKipServer) Get(ctx context.Context, req *GetRequest) (*APIReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedKipServer) Delete(ctx context.Context, req *DeleteRequest) (*APIReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedKipServer) GetLogs(ctx context.Context, req *LogsRequest) (*APIReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (*UnimplementedKipServer) Dump(ctx context.Context, req *DumpRequest) (*APIReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dump not implemented")
}
func (*UnimplementedKipServer) Deploy(srv Kip_DeployServer) error {
	return status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}
func (*UnimplementedKipServer) StreamLogs(req *StreamLogsRequest, srv Kip_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (*UnimplementedKipServer) Exec(srv Kip_ExecServer) error {
	return status.Errorf(codes.Unimplemented, "method Exec not implemented")
}
func (*UnimplementedKipServer) Attach(srv Kip_AttachServer) error {
	return status.Errorf(codes.Unimplemented, "method Attach not implemented")
}

func RegisterKipServer(s *grpc.Server, srv KipServer) {
	s.RegisterService(&_Kip_serviceDesc, srv)
}

func _Kip_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KipServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kip/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KipServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kip_IsLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsLeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KipServer).IsLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kip/IsLeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KipServer).IsLeader(ctx, req.(*IsLeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kip_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KipServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kip/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KipServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kip_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KipServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kip/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KipServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kip_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KipServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kip/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KipServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kip_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KipServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kip/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KipServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kip_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KipServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kip/GetLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KipServer).GetLogs(ctx, req.(*LogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kip_Dump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KipServer).Dump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kip/Dump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KipServer).Dump(ctx, req.(*DumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kip_Deploy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KipServer).Deploy(&kipDeployServer{stream})
}

type Kip_DeployServer interface {
	SendAndClose(*APIReply) error
	Recv() (*DeployRequest, error)
	grpc.ServerStream
}

type kipDeployServer struct {
	grpc.ServerStream
}

func (x *kipDeployServer) SendAndClose(m *APIReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *kipDeployServer) Recv() (*DeployRequest, error) {
	m := new(DeployRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Kip_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KipServer).StreamLogs(m, &kipStreamLogsServer{stream})
}

type Kip_StreamLogsServer interface {
	Send(*StreamMsg) error
	grpc.ServerStream
}

type kipStreamLogsServer struct {
	grpc.ServerStream
}

func (x *kipStreamLogsServer) Send(m *StreamMsg) error {
	return x.ServerStream.SendMsg(m)
}

func _Kip_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KipServer).Exec(&kipExecServer{stream})
}

type Kip_ExecServer interface {
	Send(*StreamMsg) error
	Recv() (*StreamMsg, error)
	grpc.ServerStream
}

type kipExecServer struct {
	grpc.ServerStream
}

func (x *kipExecServer) Send(m *StreamMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *kipExecServer) Recv() (*StreamMsg, error) {
	m := new(StreamMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Kip_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KipServer).Attach(&kipAttachServer{stream})
}

type Kip_AttachServer interface {
	Send(*StreamMsg) error
	Recv() (*StreamMsg, error)
	grpc.ServerStream
}

type kipAttachServer struct {
	grpc.ServerStream
}

func (x *kipAttachServer) Send(m *StreamMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *kipAttachServer) Recv() (*StreamMsg, error) {
	m := new(StreamMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Kip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Kip",
	HandlerType: (*KipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Kip_GetVersion_Handler,
		},
		{
			MethodName: "IsLeader",
			Handler:    _Kip_IsLeader_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Kip_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Kip_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Kip_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Kip_Delete_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _Kip_GetLogs_Handler,
		},
		{
			MethodName: "Dump",
			Handler:    _Kip_Dump_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deploy",
			Handler:       _Kip_Deploy_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _Kip_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _Kip_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Attach",
			Handler:       _Kip_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "clientapi.proto",
}
