apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: provider
spec:
  template:
    spec:
      containers:
      - name: kip
        envFrom:
        - secretRef:
            name: provider-secret
