/*
Copyright 2019 Elotl Inc.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/elotl/kip/pkg/k8sclient/clientset/versioned/typed/kip/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKiyotV1beta1 struct {
	*testing.Fake
}

func (c *FakeKiyotV1beta1) Cells() v1beta1.CellInterface {
	return &FakeCells{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKiyotV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
